config/routes.rb
Rails.application.routes.draw do
  root to: 'application#index'

  #log in and log out
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  #log in with google omniauth
  get '/auth/google_oauth2/callback' => 'sessions#create'


  resources :users, only: [:show, :new, :create] do
    resources :runs
  end

  resources :routes

  get '/runs/total_run_time', to: 'runs#total_run_time'

  get 'stats', to: 'application#stats'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/route.rb
class Route < ApplicationRecord
  has_many :runs
  has_many :users, through: :runs
  belongs_to :creator, class_name: :User

  validates :title, presence: true, uniqueness: true
  validates :location, presence: true
  validates :distance, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :elevation, presence: true, numericality: { only_integer: true }
  validates :description, presence: true

  # routes with the most runs, for stats page
  scope :most_popular_route, -> { Route.joins(:runs).group(:routes).order(
    Arel.sql('count(routes.id) desc')).first}
end

app/models/run.rb
class Run < ApplicationRecord
  belongs_to :user
  belongs_to :route

  # total time spent running, for stats page
  scope :total_run_time, -> { sum(:run_time) }

  validates :title, presence: true
  validates :date, presence: true
  validates :run_time, presence: true, numericality: { greater_than_or_equal_to: 0.1}
  validates :mood, presence: true, format: { without: /[0-9]/,
    message: "does not allow numbers" }

  validates :user_id, presence: true, numericality: { only_integer: true }
  validates :route_id, presence: true, numericality: { only_integer: true }

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password validations: false
  has_many :runs
  has_many :routes, through: :runs
  has_many :routes, foreign_key: :creator_id

  # user who has run the most miles (for stats page)
  scope :most_miles_run, -> { joins(runs: :route).group(:id).order(
    Arel.sql('sum(routes.distance) desc')).first }

  validates :email, uniqueness: true, presence: true, format: { with:
    /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}

  validates :password, confirmation: true, unless: :from_omniauth?
  validates :password, length: { minimum: 8 }, unless: :from_omniauth?

  validates :first_name, presence: true, format: { without: /[0-9]/,
    message: "does not allow numbers" }

  def from_omniauth?
    !self.uid.nil?
  end

  def been_on_run(run)
    # used to authorize users to see runs
    self.runs.include?(run)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper

  def index
    @user = current_user
  end

  def stats
    @user_most_miles = User.most_miles_run
    @total_time = Run.total_run_time
    @most_popular_route = Route.most_popular_route
  end

  private

  def require_login
    return redirect_to login_path unless session.include? :user_id
  end

end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController

  before_action :require_login
  before_action :set_route, only: [:show, :edit, :update, :destroy]
  before_action :forbid_if_not_creator, only: [:edit, :update, :destroy]


  def index
    @routes = Route.all
  end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)
    @route.creator = current_user

    @route.save ? (redirect_to route_path(@route)) : (render :new)
  end

  def show
    @user = current_user
  end

  def edit
  end

  def update
    if @route.update(route_params)
      redirect_to route_path(@route)
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to routes_path
  end

  private

  def route_params
    params.require(:route).permit(:title, :location, :distance, :elevation,
      :description)
  end

  def set_route
    # helper to find a given route by id param of page accessed
    @route = Route.find_by(id: params[:id])
    redirect_if_route_does_not_exist
  end

  def redirect_if_route_does_not_exist
    # check if someone is trying to access a page that doesn't exist & redirect
    if @route.nil?
      flash[:alert] = 'Route not found'
      return redirect_to routes_path
    end
  end

  def forbid_if_not_creator
    # only allows the creator of the route to make edits/destroy
    return head(:forbidden) unless @route.creator == current_user
  end

end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  include RunsHelper

  before_action :require_login, :set_user
  before_action :set_all_routes, only: [:new, :create, :edit]
  before_action :set_run, only: [:show, :edit, :update, :destroy]
  before_action :forbid_if_user_hasnt_been_on_run, only: [:show, :edit, :update, :destroy]


  def index
    @runs = @user.runs
  end

  def show
  end

  def new
    @run = @user.runs.build
  end

  def create
    @run = @user.runs.build(run_params)

    @run.save ? (redirect_to user_run_path(@user, @run)) : (render :new)
  end

  def edit
  end

  def update
    if @run.update(run_params)
      redirect_to user_run_path(current_user, @run)
    else
      render :edit
    end
  end

  def destroy
    @run.destroy
    redirect_to user_runs_path(current_user)
  end

  private

  def run_params
    params.require(:run).permit(:user_id, :route_id, :title, :mood, :run_time,
      :date, :notes, :conditions)
  end

  def set_user
    @user = current_user
  end

  def set_all_routes
    @routes = Route.all
  end

  def set_run
    # helper to find a given run by id param of page accessed
    @run = Run.find_by(id: params[:id])
    redirect_if_run_does_not_exist
  end

  def forbid_if_user_hasnt_been_on_run
    # runs before each action except new/create to check that this user is
    # authorized to access this run
    return head(:forbidden) unless current_user.been_on_run(@run)
  end

  def redirect_if_run_does_not_exist
    # check if someone is trying to access a page that doesn't exist & redirect
    if @run.nil?
      flash[:alert] = 'Run not found'
      return redirect_to user_runs_path(current_user)
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    if auth
      @user = User.find_by(email: auth['info']['email'])
      if @user.nil?
        @user = User.new(email: auth['info']['email'], uid: auth['uid'],
          first_name: auth['info']['first_name'])
        @user.save
      end
    else
      @user = User.find_by(email: params[:user][:email])

      return head(:forbidden) unless @user.authenticate(params[:user][:password])
    end

    session[:user_id] = @user.id
    redirect_to root_path
  end

  def destroy
    session.delete :user_id if session[:user_id]     # logout
    redirect_to login_path
  end

  private

  def auth
    request.env['omniauth.auth']
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :first_name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

end

app/helpers/runs_helper.rb
module RunsHelper

  def run_date(run)
    run.date.strftime("%A, %B %e")
  end

  def format_run_time(run_time)
    total_seconds = run_time * 60
    Time.at(total_seconds).utc.strftime("%H:%M:%S")
  end

end

app/views/application/index.html.erb
<h1> Welcome to Running Club! </h1>
<% if logged_in? %>
  <%= link_to 'View running routes', routes_path %> </br>
  <%= link_to 'My runs', user_runs_path(@user) %> </br>
  <%= link_to 'Fun Stats', stats_path %> </br>


  <%= link_to "Log Out", logout_path, method: :delete, data: { confirm: "Really?" } %>

<% else %>

  <%= link_to 'Signup', new_user_path %> </br>
  <%= link_to 'Log in', login_path %> </br>
  <%= link_to('Log in with Google!', '/auth/google_oauth2') %>


<% end %>

app/views/application/stats.html.erb
<h1> Running App Stats </h1>

<ul>
<li> The user who has run the most miles is <%= @user_most_miles.first_name %></li>
<li> Users have spent a total of <%= format_run_time @total_time %> running!</li>
<li> The most popular route is  <%= @most_popular_route.title %></li>

</ul>

<%= link_to "Go Back", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RunningApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/routes/_form.html.erb
<%= form_for @route do |f| %>
  Title: <%= f.text_field :title,
    placeholder: @route.errors.full_messages_for(:title).first %> </br>
  Location: <%= f.text_field :location,
    placeholder: @route.errors.full_messages_for(:location).first %> </br>
  Distance (miles): <%= f.number_field :distance,
    placeholder: @route.errors.full_messages_for(:distance).first %> </br>
  Elevation (feet): <%= f.number_field :elevation,
    placeholder: @route.errors.full_messages_for(:elevation).first %> </br>
  Description: <%= f.text_field :description,
    placeholder: @route.errors.full_messages_for(:description).first %> </br>
  <%= f.submit "Submit" %>
<% end %>

app/views/routes/edit.html.erb
<h1> Edit <%= @route.title %>:</h1>
<%= render 'form' %>

app/views/routes/index.html.erb
<h1> Route Information </h1>
<% flash.each do |name, msg| -%>
   <%= content_tag :div, msg, class: name %>
 <% end -%>

<% @routes.each do |r| %>
  <%= link_to r.title, route_path(r) %> </br>
<% end %>
</br>

<%= link_to 'Add new route', new_route_path %> |
<%= link_to 'Go back', root_path %>

app/views/routes/new.html.erb
<h1> Add a new route:</h1>

<%= render 'form' %>

app/views/routes/show.html.erb
<h1><%= @route.title %></h1>
Location: <%= @route.location %> </br>
Distance: <%= @route.distance %> miles</br>
Elevation: <%= @route.elevation %> feet </br>
Description: <%= @route.description %> </br>

<% if @route.creator == current_user %>
 <%= link_to "Edit", edit_route_path(@route) %> |
 <%= link_to "Delete", @route, method: :delete, data: { confirm: "Really?" } %>
<% end %>
 </br>
 </br>
<%= link_to "See all routes", routes_path %>

app/views/runs/_form.html.erb
<%= form_for ([@user, @run]) do |f| %>
  <%= f.hidden_field :user_id %>
  Give this run a name <%= f.text_field :title,
    placeholder: @run.errors.full_messages_for(:title).first %> </br>
  When was your run? <%= f.date_select :date %> </br>
  What route did you run? <%= f.collection_select :route_id, @routes, :id, :title %> </br>
  How long did you run for? (in minutes) <%= f.number_field :run_time, step: :any,
    placeholder: @run.errors.full_messages_for(:run_time).first %> </br>
  How did you feel? <%= f.text_field :mood,
    placeholder: @run.errors.full_messages_for(:mood).first %> </br>
  How were the running conditions? <%= f.text_field :conditions %> </br>
  Anything to note? <%= f.text_field :notes %> </br>
  <%= f.submit "Submit" %>
<% end %>

app/views/runs/edit.html.erb
<h1> Edit run </h1>
<%= render 'form' %>

app/views/runs/index.html.erb
<h1>My Runs</h1>
<% flash.each do |name, msg| -%>
   <%= content_tag :div, msg, class: name %>
 <% end -%>

<% @runs.each do |r| %>
  <%= run_date(r) %> -
  <%= link_to r.title, user_run_path(@user, r) %> </br>
<% end %>
</br>

<%= link_to 'Add new run', new_user_run_path(@user) %> |
<%= link_to 'Go back', root_path %>

app/views/runs/new.html.erb
<h1> Add a new run </h1>

<%= render 'form' %>

app/views/runs/show.html.erb
<h1><%= @run.title %></h1>
Date run: <%= run_date @run %> </br>
Route: <%= @run.route.title %> </br>
Run Time: <%= format_run_time @run.run_time %> </br>
Mood: <%= @run.mood %> </br>
Conditions: <%= @run.conditions %> </br>
Notes: <%= @run.notes %> </br>


<% if current_user.been_on_run(@run) %>
<%= link_to "Edit", edit_user_run_path(@user, @run) %> |
<%= link_to "Delete", [@user, @run], method: :delete, data: { confirm: "Really?" } %>
<% end %>

</br>
</br>
<%= link_to "See all my runs", user_runs_path(@user) %>

app/views/users/new.html.erb
<h1> Sign up for Running Club </h1>

<%= form_for @user do |f| %>
  Email: <%= f.text_field :email,
    placeholder: @user.errors.full_messages_for(:email).first %> </br>
  Name: <%= f.text_field :first_name,
    placeholder: @user.errors.full_messages_for(:first_name).first %> </br>
  Password: <%= f.password_field :password,
    placeholder: @user.errors.full_messages_for(:password).first %> </br>
  Password Confirmation: <%= f.password_field :password_confirmation,
    placeholder: @user.errors.full_messages_for(:password_confirmation).first %> </br>
  <%= f.submit "Sign up" %>
<% end %>